services:
  localstack:
    image: localstack/localstack:3.0
    container_name: postgres-replication-localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=secretsmanager,iam
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localstack
    volumes:
      - "./localstack-init:/etc/localstack/init/ready.d"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - postgres-replication-net

  redis:
    image: redis:7-alpine
    container_name: postgres-replication-redis
    ports:
      - "6379:6379"
    networks:
      - postgres-replication-net

  postgres-primary:
    image: postgres:15
    container_name: postgres-replication-primary
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=10
      -c max_wal_senders=10
      -c shared_preload_libraries=pg_stat_statements
    networks:
      - postgres-replication-net
    volumes:
      - postgres-primary-data:/var/lib/postgresql/data
      - ./docker-init/primary-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./docker-init/pg_hba.conf:/docker-entrypoint-initdb.d/pg_hba.conf
      - ./docker-init/setup-pg-hba.sh:/docker-entrypoint-initdb.d/02-setup-pg-hba.sh
      - ./docker-init/02-setup-replication.sh:/docker-entrypoint-initdb.d/02-setup-replication.sh

  postgres-replica:
    image: postgres:15
    container_name: postgres-replication-replica
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
    command: >
      postgres
      -c wal_level=logical
      -c max_replication_slots=10
      -c max_wal_senders=10
      -c shared_preload_libraries=pg_stat_statements
    networks:
      - postgres-replication-net
    volumes:
      - postgres-replica-data:/var/lib/postgresql/data
      - ./docker-init/replica-init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./docker-init/pg_hba.conf:/docker-entrypoint-initdb.d/pg_hba.conf
      - ./docker-init/setup-pg-hba.sh:/docker-entrypoint-initdb.d/02-setup-pg-hba.sh
    depends_on:
      - postgres-primary

  postgres-physical-replica:
    image: postgres:15
    container_name: postgres-replication-physical-replica
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=testpass
    networks:
      - postgres-replication-net
    volumes:
      - postgres-physical-replica-data:/var/lib/postgresql/data
      - ./docker-init/setup-physical-replica.sh:/setup-physical-replica.sh
      - ./docker-init/pg_hba.conf:/pg_hba.conf
    command: ["bash", "/setup-physical-replica.sh"]
    depends_on:
      - postgres-primary

  replication-setup:
    image: postgres:15
    container_name: postgres-replication-setup
    networks:
      - postgres-replication-net
    volumes:
      - ./docker-init/setup-subscription.sh:/setup-subscription.sh
      - ./docker-init/configure-auth.sh:/configure-auth.sh
    command: ["bash", "-c", "/configure-auth.sh && /setup-subscription.sh"]
    depends_on:
      - postgres-primary
      - postgres-replica
      - postgres-physical-replica

volumes:
  postgres-primary-data:
  postgres-replica-data:
  postgres-physical-replica-data:

networks:
  postgres-replication-net:
    driver: bridge